[project]
name = "video-to-essay"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.79.0",
    "imagehash>=4.3.2",
    "opencv-python>=4.13.0.92",
    "pillow>=12.1.1",
    "typer>=0.23.0",
    "youtube-transcript-api>=1.2.4",
    "yt-dlp>=2026.2.4",
]
